### ISSUE TITLE
Proposed redefining of priorities for this repo

### ISSUE THREAD

**Issue by iteles** [dwyl/hq#349] opened 2017-06-04 19:18 UTC
As a person who is frequently assigned to issues in the `hq` repo, I need everyone to be _clear_ on what the various labels mean so that I don't end up disregarding them because they are misused.

Case in point: there are 23 `priority-1` issues assigned to me. If something _truly important_ is assigned to me, there is now no way of communicating that.

"Everything is a top priority" is the kind of BS I spend _days_ of my life coaching clients out of.

This particular repo is a little insane:
<img width="456" alt="screen shot 2017-05-27 at 22 03 46" src="https://cloud.githubusercontent.com/assets/4185328/26525521/b10d1888-4351-11e7-9649-f67bc05d16d1.png">

Suggested course of action:
+ [ ] Demote *everything* in this repo by 1 priority level
+ [ ] Agree what constitutes each priority level
+ [ ] Add a note to the readme with the agreed levels

## Proposed levels:
+ `priority-1` used _only_ for emergencies and things that need to get done _in the next 48 hours_
  + These issues have to have a clear deadline and 'why?' in the description
  + This label is a "drop everything and do this" label, so be _careful_ when assigning to other people's assigned issues
  + Sometimes these will be things that are unexpected
+ `priority-2` for issues that need to be carried out _this week_
+ `priority-3` for things that are important and should be next on the list
  + Issues should not sit in this priority bucket for more than 4 weeks without review, at which point they need to be promoted to p2, demoted to p4 or have a comment added as to why they are still p3
+ `priority-4` for things that need to be fully discussed and agreed but the overall feeling is they should be carried out in the coming months 
+ `priority-5` for things that are just ideas 
  + This list should be reviewed once a month
  + Once a discussion has been had, they are promoted to the appropriate priority or left in p5 as a back-burner conversation

**Comment by markwilliamfirth** [comment] 2017-06-05 08:55
@iteles we could always make a priority-0 label 😆

**Comment by markwilliamfirth** [comment] 2017-06-05 11:17
<img width="992" alt="screen shot 2017-06-05 at 12 16 25" src="https://cloud.githubusercontent.com/assets/5732209/26781908/d659a7e4-49e8-11e7-9f9b-6a81a583a893.png">

@iteles I have cleared my p1s in-line with suggestion in this issue

**Comment by Jbarget** [comment] 2017-06-05 11:35
@iteles I think it may be confusing for us as during sprints we assign priorities based on the order they need to be done. I imagine most teams start by adding `priority-1` labels to the "scaffolding" of the project, not because its time critical (I guess a sprint is always time critical) but because its intuitive.

So having the same labels `priority-n` for both admin and dev work might be confusing as they're being used in different ways across the organisation.

**Comment by iteles** [comment] 2017-06-05 13:54
@markwilliamfirth 😬 This is still very much an open proposal!
The idea was to downgrade everything at once as that's a bit easier in the github interface. 

@Jbarget In my experience priority 1 (the sky is falling, drop everything and do just this) and priority 5 (just an idea) are used in the same way across all dwyl projects. priority 2s also tend to be 'these are important and need to be done next' issues. It's the 3s and 4s that are slightly different and from what I've seen, these are a little subjective from project to project.
Having one system that works for both is ideal, I'm proposing we trial this approach to see if it does work. You're very right in that it might not, but I'd like to test it out 😊

**Comment by Jbarget** [comment] 2017-06-05 14:07
ah definitely! I didnt mean to imply that it wont work, was just giving my experience of things :)

#onesystemtorulethemall

**Comment by nelsonic** [comment] 2017-06-05 14:44
Priority and Urgency are related but different. 

I would _suggest_ having a deadline `metadata` in the issue title and/or description to aid with prioritisation. 

I _agree_ that having _too many_ `priority-1` issues "_devalues_" the importance of the label.
But I don't think "_downgrading_" the priority of all issues is a _good_ way to "_solve_" this.

We should _definitely_ be _clear_ on what a `priority-1` issue _means_ within @dwyl 
and to _me_ that means _anything_ that is costing/losing us money each day that goes by.

For example: Focus Hub is costing us **_real_ money** each _day_ because it's not got enough paying customers ... Yet, this is not identified as a `priority-1` issue in FocusHub:
https://github.com/dwyl/focushub/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Apriority-1
![image](https://cloud.githubusercontent.com/assets/194400/26787707/e65a1812-4a02-11e7-862d-7e7756f86e12.png)
I cannot see an issue mentioning the word FocusHub on HQ:
https://github.com/dwyl/hq/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20focushub
![image](https://cloud.githubusercontent.com/assets/194400/26787923/7a5eacbc-4a03-11e7-8ccf-6e78738a1163.png)
Or https://github.com/dwyl/hq/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20quietspace%20
![image](https://cloud.githubusercontent.com/assets/194400/26787987/b030686c-4a03-11e7-8644-a9bade933ae8.png)
The _empty_ ("_half-full_" _if you prefer_) co-working space is the second most costly thing... 💸 

As for the other issues marked as `priority-1` they are _all_ costing us money each day that goes by without them being `done`, so they fit _my_ criteria for "highest priority". 

ideally we should have an internal "triage" system for determining how _much_ money is being lost each day the issue is not _resolved_, and order the issues based on that number.
and eventually get down to _zero_ `priority-1` issues.

**Comment by iteles** [comment] 2017-06-05 15:04
There were at least 3 priority 1 issues on FH related to things that were related to getting more people in. Not sure what happened there...

Agree that priority isn't just about urgency.
Whether or not something is costing us money or upsetting dwylers is actually how I determine how quickly we need to take action on something. This is why accounts #229 and #182 have been `priority-1` issues since early February.

I'm _assuming_ these haven't been complete yet _because_ the value of the p1 label has been diluted massively by the problem I'm outlining above, hence this issue.

I seem to have left off the last step in the plan from the above: review the p2s and determine if any are priority 1s. For me, #229 (of which #321 is the first step) and #182 have been the highest priority for 4 months and would remain that way.

**Comment by markwilliamfirth** [comment] 2017-10-26 14:13
@iteles what's the next step in this issue?

**Comment by markwilliamfirth** [comment] 2017-10-26 16:39
After reviewing the backlog this doesn't appear to be an issue anymore (plz reopen if you disagree)

**Comment by iteles** [comment] 2018-02-06 19:50
Reopening as the `priority-1` issues mentioned in https://github.com/dwyl/hq/issues/349#issuecomment-306211324 were still not addressed almost 5 months later when this issue was closed, so it's clearly still an issue.

**Comment by rub1e** [comment] 2018-02-07 08:58
> I say, beware of all enterprises that require new clothes, and not rather a new wearer of clothes.

The lines will always be blurred, but the definitions seem sensible to me. Perhaps they weren't the issue

**Comment by iteles** [comment] 2018-02-07 09:39
@gregaubs 😄 The definitions aren't the issue, the issue is they haven't yet been applied 😛

**Comment by nelsonic** [comment] 2019-01-18 20:10
This issue has _way_ too much _noise_ from "Ghost". Closing.
GOTO: https://github.com/dwyl/labels/issues/87

**Closed by nelsonic** 2019-01-18 20:10 UTC
Labels: chore, discuss, question
