### ISSUE TITLE
dwyl Companies House Filings

### ISSUE THREAD

**Issue by ghost** [dwyl/hq#262] opened 2017-02-27 11:55 UTC
- [x] Cap Table - [Google Sheet](https://docs.google.com/spreadsheets/d/1dqOnmrVCDXUAPQ0-5P6be_L-jgPVhRDhXBXgCmHMtU8/edit#gid=0)

- [x] SH02 - [PDF](https://drive.google.com/open?id=0B0XeQ2t5WSK2SUE0QU12bXpsSjg)

- [x] SH01 - [PDF](https://drive.google.com/open?id=0B0XeQ2t5WSK2bFRBcnA0ZWhOU3c)

- [x]  Articles of Association - [Word Doc](https://drive.google.com/open?id=0B0XeQ2t5WSK2dVFJOUtmQTgzUlk), [Google Doc](https://docs.google.com/document/d/1LJAr-9hJk1CLbpoIRPuL8pgJDNfoVnjlywEcejb0TNA/edit#heading=h.gjdgxs) (Google Doc has poor formatting due to conversion)

- [x] Board Minutes - [Word Doc](https://drive.google.com/open?id=0B0XeQ2t5WSK2eU56eU44WXV2NEk)

- [x] Written Resolution - [Word Doc](https://drive.google.com/open?id=0B0XeQ2t5WSK2a1VxTnU3b09CLVE)

- [x] Notice of Resolution - [Word Doc](https://drive.google.com/open?id=0B0XeQ2t5WSK2MzJUMjJqaHFLWGc)

- [x] Cover Letter - [Word Doc](https://drive.google.com/open?id=0B0XeQ2t5WSK2MWN3aE10ck1fcFk)
+ [x] Final review of docs (@iteles)
+ [ ] Post final docs (@iteles)

**Comment by markwilliamfirth** [comment] 2017-02-27 12:36
@iteles @nelsonic Please can you review the [Cap Table](https://docs.google.com/spreadsheets/d/1dqOnmrVCDXUAPQ0-5P6be_L-jgPVhRDhXBXgCmHMtU8/edit#gid=0) and decide whether you would like to go with version 1 (no options) or version 2 (options)?

**Comment by nelsonic** [comment] 2017-02-28 06:47
@markwilliamfirth _thank you_ for opening this issue. 👍 
_unassigning_ myself as I don't think there's much point "_diving up the cake_" `before` it's been _baked_. 
Yes, it's _important_ to think about these things, but I don't think it's "P1" and it _certainly_ is not something ***I*** need to be focussed on until the _product_ has been shipped. ✨ 

@iteles happy for you to make any/all required decisions on this (_you have my "vote"_). ✅ 

Thanks! ❤️

**Comment by markwilliamfirth** [comment] 2017-02-28 09:21
@iteles let me know if you have any thoughts re options!

**Comment by iteles** [comment] 2017-03-01 20:25
@markwilliamfirth Just need you to talk me through the 'Add Options' portion of the spreadsheet please! Just grab me when available tomorrow :blush:

**Comment by markwilliamfirth** [comment] 2017-03-06 18:51
Inês has confirmed to proceed without options for now

**Comment by markwilliamfirth** [comment] 2017-05-05 18:25
[DWYL Articles.docx](https://github.com/dwyl/hq/files/979964/DWYL.Articles.docx)

@iteles @nelsonic please could you review the articles? These are in addition to the [model articles](https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/376832/model_articles_private_ltd_by_shares_after28April2013.doc)

**Comment by nelsonic** [comment] 2017-05-05 18:34
`.docx` ?
Don't have MS Word on my computer, sorry, @iteles do you?

**Comment by iteles** [comment] 2017-05-06 01:29
... nope @nelsonic.

**Comment by markwilliamfirth** [comment] 2017-05-08 08:16
[DWYL.Articles.pdf](https://github.com/dwyl/hq/files/982756/DWYL.Articles.pdf)
@nelsonic pdf attached

**Comment by markwilliamfirth** [comment] 2017-05-10 16:21
@nelsonic @iteles please can you review asap?

>Thank you for your email of 09/05/17 concerning the overdue confirmation statement for 02/04/17.

>As the company is required to remain on the register, the proposed strike off action has been discontinued.  The failure to file a confirmation statement is a criminal offence but I will defer any prosecution action for 28 days from the date of this letter.

>If the company record is not brought up-to-date by that time, the directors may face criminal proceedings.  Conviction for this offence will result in a criminal record and a potential unlimited fine for each document not delivered on time.

**Comment by iteles** [comment] 2017-05-11 11:51
@markwilliamfirth How do you want us to add our comments? Would a google doc not be possible?

**Comment by markwilliamfirth** [comment] 2017-05-11 12:32
@iteles feel free to print out and write comments or convert the file to whatever format you wish to add comments. When I make the changes I will do so in the word doc as converting to another format such as a [google doc](https://docs.google.com/document/d/1yNGSpUc4gE9AtCpyl5ZRjVHBMjlU7mon5OGv3i5WRYg/edit#) will disrupt the formatting of the current document as in this linked example

**Comment by iteles** [comment] 2017-05-11 14:04
I won't review for formatting, just the content 👍 

At client site today so can't print and also 🌴 🌲 🌳 🎄 ♻️  😉

**Comment by nelsonic** [comment] 2017-05-17 05:52
I made a mistake. 
And now we are focussing on _totally_ the wrong thing.
I _honestly_ thought that we would be focussing on _making_ the "pie" not how to "_slice_" it

**Comment by nelsonic** [comment] 2017-05-23 15:14
I don't think I _need_ to be assigned to this issue. 
I _still_ think this is a _massive_ distraction from getting _real_ work done. (_**shipping** the **product**_)
If my `input` is required please mention me.

**Comment by markwilliamfirth** [comment] 2017-05-24 08:32
@nelsonic this isn't a distraction - this issue is currently holding back adding me to the co-op bank and filing the company's annual confirmation statement. The former of which could mean our bank account may be closed unless we move fast and the latter of which may mean the company will be shut down by companies house unless we move fast. The only reason your input is required is because you will be required to sign documents and agree with them.

**Comment by markwilliamfirth** [comment] 2017-05-24 08:33
@iteles have you completed your review? Are you happy for me to make the required changes and proceed with filing?

**Comment by iteles** [comment] 2017-05-24 10:01
It's my top priority today @markwilliamfirth, so worth getting everything else ready for filing :+1:

**Comment by iteles** [comment] 2017-05-25 19:42
I left a question yesterday and a few more comments today 👍

**Comment by markwilliamfirth** [comment] 2017-06-01 14:19
@iteles updated articles [here](https://docs.google.com/document/d/1LJAr-9hJk1CLbpoIRPuL8pgJDNfoVnjlywEcejb0TNA/edit)

**Comment by iteles** [comment] 2017-06-01 15:24
@markwilliamfirth 👍 Will review tonight

**Comment by markwilliamfirth** [comment] 2017-06-01 16:52
Completed. Inês to make a final review + sign tonight. Docs to be sent to:

The Registrar of Companies, Companies House,
Crown Way, Cardiff, Wales, CF14 3UZ.
DX 33050 Cardiff

**Comment by iteles** [comment] 2017-06-03 08:30
@markwilliamfirth I couldn't review it from Thursday to Friday as it wasn't planned in and didn't get through my non-moveable planned activities in time to fit it in.

When going through it on Friday night/Saturday morning I spotted 2 incorrect things I hadn't picked up on in the electronic copy which need amending in the paper copy and 2 unresolved questions in the electronic copy that we should discuss.

I picked up a next day delivery envelope from the post office so let's catch up on Monday and we can drop it off for a guaranteed delivery on the 6th and a filing of the confirmation statement #288 on the evening of 6th June (so we can call the coop and tell them it's done first thing on the 7th June). **I would suggest we call the Coop Bank on 5th June to let them know this will be done.**

**Comment by markwilliamfirth** [comment] 2017-06-03 09:25
The deadline isn't to do with the coop, it's relevant to companies house. I will email CH again. Please can you plan in 1h of review time on Monday?

**Comment by iteles** [comment] 2017-06-05 14:28
This morning I printed off the amended copy, signed and went to the post office and stood in line for 20 mins to post this. Next day delivery, will be there tomorrow.

**Comment by iteles** [comment] 2017-12-08 01:01
@rub1e If you have some time next week to give me a hand with this whilst I sort out #229, that would be grand! 

Reopening this issue rather than opening a new one so as we already have the steps and the history logged here (this makes me happy we do everything in issues 🎉 )

**Comment by rub1e** [comment] 2017-12-08 10:12
@iteles Yup! I appear to have access to all the... _word_ documents :confused: - haven't seen a `.docx` since the old days :smiley:

**Comment by iteles** [comment] 2018-04-15 12:47
@rub1e Annual confirmation going in on Monday #458 so we can finalise these docs and get them sent to CH 🎉

**Comment by nelsonic** [comment] 2018-05-29 11:19
@iteles I counter-signed the resolutions this morning 🖊 [>](https://en.wikipedia.org/wiki/The_pen_is_mightier_than_the_sword) 🔪
if you take them with you to Space4 tmrw, @rub1e can send. ✉️ 
(_thanks **both** for doing this ..._)

**Comment by rub1e** [comment] 2018-05-29 13:05
I feel really bad because I'd asked @iteles to put them in a folder for me and she actually had but I'd forgotten about this whole thing.

I think there's a post office on my way in so I'll file them in the morning (30/5)

**Comment by rub1e** [comment] 2018-05-30 16:46
Sent. Will close after confirmation from CH

**Comment by rub1e** [comment] 2018-06-12 09:59
Updated `Articles of Association` now appear on our Companies House listing so this is now complete

**Closed by rub1e** 2018-06-12 09:59 UTC
Labels: T4h, dependency, priority-1
