### ISSUE TITLE
dwyl apprenticeship

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hq#356] opened 2017-06-09 20:12 UTC
_Several_ people have asked what the _specifics_ of the dwyl internship are. 
Here are some details, if you have any further questions please leave comments below. (_thanks!_)

# The Question(s) People Need to Answer `before` Joining/Working With @dwyl

The most important question we have to ask (_and get **written**_) answers to are:

## About You (_the Apprentice_)

+ [ ] ***Who*** are ***you***?
+ [ ] **What** is _your_ "***story***" (_or "journey"_) so far? 
  + [ ] Where have you worked `before`?
  + [ ] What did you like/dislike about working there?
  + [ ] What did you learn (_both good and bad_!) while there?
+ [ ] ***What*** do you want to do with the next **2 years** of your **life**?
  + [ ] ***Where*** do you want to live?
+ [ ] Is there a "***Real World Problem***" you would like to solve?
  + [ ] What is your _personal connection_ to the problem?
+ [ ] ***Why*** do you ***want*** to **work** _with_ @dwyl ***specifically*** (_as opposed to the **millions** of other options you have_) ?

## Prerequisites 

+ [ ] Answer the "AMA" Questions (_above_)
+ [ ] Existing contribution to a dwyl `learn-...` repository in the form of questions (_and preferably a Pull Request_)
+ [ ] Desire/willingness to learn the technologies in the dwyl "PETE" stack: https://github.com/dwyl/technology-stack 
+ [ ] ***Proactiveness*** following the dwyl contribution "workflow": https://github.com/dwyl/contributing

## The (Mini) Projects

+ [ ] Learner Map (_introductory/fun project to display all people using dwyl tools/tutorials on a world map on our big screen and website!_)
  + [ ] Mentored by @eliascodes (_possibly, if I ask him nicely..._) 
  + [ ] Using Google Maps to plot a few hundred points on a World Map based on frequency/density
  + [ ] Geocode names of places for a 4k people using GeoNames API ... tutorial: https://github.com/numo-labs/lambda-taggable-geonames-indexer
> Note: we _could_ simply use [Google Fusion Tables](https://support.google.com/fusiontables/answer/2527132?hl=en&topic=2573107&ctx=topic) for this. e.g: https://visualign.wordpress.com/2011/06/08/google-fusion-tables-free-visualization-tool (_I have used Fusion Tables in the past and it's quite good/easy. The main thing is we want to make it Interactive and embed it on the dwyl.com website and we need to be able to update it easily so Fusion Tables might not be suitable..._)
+ [ ] dwyl **Progressive Web App** https://github.com/dwyl/time
  + [ ] Working with (_mentored by_) @sohilpandya (& Nelson)
  + [ ] Create a PWA of dwyl's "Time & Task" Management App 
  + [ ] Built in Elm (_using PWA toolkit_) and Swift for ***Native Notifications*** on iOS
  + [ ] using the dwyl API: https://github.com/dwyl/api
+ [ ] Project (GitHub) **Chat** (_what "Gitter" **could** have been_!) see: https://github.com/dwyl/chat/issues/37 
  + [ ] Mentored by @katbow 
+ [ ] "***dwylbot***" Workflow Automation (_some elixir learning required_) https://github.com/dwyl/dwylbot
  + [ ] Mentored by @SimonLab

**Comment by iteles** [comment] 2017-06-09 22:01
Note: budget for this approved in February/March when first discussed with D. Sofer.

**Comment by ZooeyMiller** [comment] 2017-06-11 16:37
Hi! should I just comment here with my AMA answers or send them to anyone in particular?

**Comment by ZooeyMiller** [comment] 2017-06-11 18:07
Oh! Also, do you know when the apprenticeship would start and/or end?

**Comment by ZooeyMiller** [comment] 2017-06-12 12:15
#### Who are you?
:wave: I'm Zooey. I just graduated from Founders and Coders 10.
#### What's your story?
Before coming to Founders and Coders I was working as a bike mechanic and teacher at [London Bike Kitchen](http://www.lbk.org.uk/), and working as a supervisor at Lush Fresh Handmade Cosmetics.

I _love_ working with bicycles, and fixing things. I really liked teaching people how to fix their own bikes, and seeing their satisfaction in the demystification of this thing they used every day. Unfortunately bike mechanics do not get paid very well, and unless you want to open your own shop, there isn't really any career progression there, so it wasn't really sustainable.

Working at Lush was a way for me to work out what I wanted to do, my passion isn't specifically in cosmetics, but I really loved working at a company which was environmentally conscious, worked hard to support and look after their workers, and emphasise internal progression. I suppose the main thing I didn't like was being a salesperson, it's not really for me!

At LBK I learned a lot about adult education, I really believe in the ability to access good and useful knowledge, and us as a society removing this kind of looking down on people who don't know things.

![](https://imgs.xkcd.com/comics/ten_thousand.png)

I also learned about how a small business can suffer when things aren't going very well. We had a lot of times where we struggled with money becuase we were providing a service that was expensive to provide, but people did not want to pay enough for. This made me value good management, and industries with high perceived value from a consumer perspective.

#### What do you want to do with the next 2 years?
In terms of my work life I would like to continue learning and working in web development, ideally working predominantly on Tech for Good projects. I really believe in technology's ability to make people's lives better and I'd love if I could work in that field. I want to be in environments with experienced developers who I can learn from and work with.

Outside of work I want to carry on with self supported ultra-distance bicycle racing. I completed the [Transatlantic Way](http://www.transatlanticway.com/) last year, and I want to aim for the [Highland Trail 550](http://www.highlandtrail.net/) and/or the [French Divide](http://www.frenchdivide.com/en/) next year, and my big goal is [The Tour Divide](http://tourdivide.org/) (4400km of off-road racing, from Canada to Mexico).

For at least the next two years I see myself living in London. At some point in the future I see myself living elsewhere, even if it's only temporarily, but that's a while off yet.

#### A real world problem
A genuine real world problem would be convincing people who are self-deprecating/have low self esteem that they are good enough and that they can do things. So often the mindset of people in these situations ends up being "I can't do it", whether that's because they've told themselves that or because other people have told them that in their life. This comes before even trying, attempting to bridge that gap between "I'm interested in X thing" to _actually_ trying that thing would be amazing.

My personal connection would be the way I view myself and the way I think about myself. I can be pretty down on myself. I've managed to work myself into an attitude of "I will probably fail but I'd rather try, then fail, than not try at all", where I feel a lot of people still think "I will probably fail, so what's the point in trying."

I suppose the most logical place to start with this would be specifically regarding getting into coding, but I think it's an important problem in pretty much any field.

#### Why dwyl?
I want to work with dwyl becuase I think that the dedication to open source and providing accessible tutorials for getting people into web development is amazing. I've had nothing but amazing experiences with the people who work at dwyl, and I would really like to take part in that community, and learn from the experienced developers who are part of it.

**Comment by Cleop** [comment] 2017-06-12 14:18
As dwyl's most recent joiner and someone who has joining the company's systems and tech stack fresh in mind...

Some things to consider including when this scheme begins:
- Introduction the dwyl git workflow (with particular emphasis on raising issues instead of asking questions, what to do if you get stuck, notifications)
- An intro to Tachyons (how to use the documentation effectively)
- Means of dealing with feedback/ human contact time

**Comment by finnhodgkin** [comment] 2017-06-12 16:59
> Who are you?

Finn Hodgkin

> What is your "story" (or "journey") so far?

Growing up I loved art, animated film and video games, so when it came to choosing a subject for university I landed on animation assuming it would be the perfect combination. It took me three years to realise it wasn't... Although I still enjoy the medium, I don't find the work very satisfying. Even with large team projects the work tends to be solitary and insanely repetitive.

The bits I did find rewarding usually involved logic or code, so towards the end of my degree I specialised in CGI rigging (the process of adding a movable skeleton and/or skin to 3D characters and objects). But this still involved too much painting vertices in 3D space and too little fun coding challenges, so I remained unengaged.

After some unsuccessful attempts at professional animation I cut my loses, went travelling and tried to come up with a life plan that I could commit to. I experimented with freelance web and print design - usually for friends of friends, of course - but I felt like I was tricking people because I'd taught myself and wasn't confident in my skill-set.

Then a friend recommended Founders and Coders, but instead of listening to him and applying, I shoved it to the back of my mind and went to work for a charitable political campaign and a couple of other third sector orgs.

As soon as they finished I remembered FAC and here I am :heart: 

> Where have you worked before?

Before the Lobbying Bill became the Lobbying Act, I worked for the Commission on Civil Society and Democratic Engagement to campaign against it. The Commission was a small team - just five or six of us - backed by a huge coalition of charities including both the Countryside Alliance _and_ Greenpeace; and the National Secular Society *__and__* the Christian Institute!

The Lobbying Bill was a thinly veiled attempt by the Conservatives to limit charitable and union campaigning during the election (it was framed as a way to remove big money from politics though there was never any evidence of this). The campaign was fought to extremely tight deadlines because the legislation was pushed through Parliament as fast as legally possible. The frantic pace meant I was constantly jumping between charities and Parliament, working on a bunch of different things ranging from research, managing the website, political and supporter databases, to writing copy and cold calling Peers and MPs. We produced three long reports, were picked up by almost every major newspaper and made significant (though not significant enough) changes to the law.

I've also worked on and off as a web and print designer for the Global Initiative to End Corporal Punishment of Children and the Children Are Unbeatable Alliance. This work was never quite sustainable, so I also undertook a steady flow of boring temp jobs.

> What did you like/dislike about working there?

I loved almost every aspect of my work for the Commission. Highlights included a piece of research I put together being read out in the House of Lords and performing detailed research on every Peer's controlling interests and links to lobbying groups (*scary*). The pressure of deadlines was never a real issue because the team was so friendly and the campaign such an important thing to support. The only parts I didn't like were witnessing corruptibility of the political process, and that in the end the campaign wasn't a total success.

I generally find design work really engaging, though the unreliable nature of freelancing was a pain and the work was weighted too heavily towards pure HTML / CSS and not code. One project I particularly enjoyed was building an easy to update [interactive map of the world](http://www.endcorporalpunishment.org/interactive-map) for the Global Initiative. This was the project that really sparked my serious interest in web development and FAC.

> What did you learn (both good and bad!) while there?

Good:
- Basic JavaScript, HTML, CSS, and some design principles.
- How to not stress in a high-pressure time-sensitive job.
- Data collection and simple database handling.

Bad:
- Politicians are just as irritating in person.
- Wordpress.

> What do you want to do with the next 2 years of your life?

My foremost aim is to become a better developer, hopefully working under the guidance of more experienced devs. Secondly I'd like to work as a developer for a charity or tech for good. Also I've loved my time with FAC so hopefully I can stay connected to that community.

> Where do you want to live?

I'm happy in London but ideally I'd like to occasionally work from my family home in Italy (it's next to a tiny town in the middle of nowhere so it's a great escape from the city).

> Is there a "Real World Problem" you would like to solve?

The voucher system at my local food bank.

In the months leading up to FAC I volunteered at a nearby food bank once a week. The way the current system works is that people in financial difficulty pick up a voucher from an organisation - the Job Centre, the Irish Centre, Citizens Advice Bureau, etc. - then bring the voucher to the food bank in exchange for a box of food. The food bank itself only gives out food, it doesn't assess need or issue vouchers.

The biggest problem with this setup is that the organisations themselves aren't allowed to print the vouchers, they have to ask the food bank to replenish their supplies every couple of months. This means that if there's a sudden influx of in-trouble people (happens pretty regularly), the different organisations have to shuffle them between buildings (not a short walk) or turn them away.

It's a ridiculous system, creates more work for everyone involved and means people can go hungry. Although the people at the different organisations are far from being tech-savvy, I'm sure there's a really simple solution.

> What is your personal connection to the problem?

Just that I was there for a while and it was a really frustrating issue.

> Why do you want to work with @dwyl specifically (as opposed to the millions of other options you have) ?

A few reasons:
- Everyone I've met from dwyl is super friendly and willing to answer ~~stupid~~ questions.
- The parts of the tech stack I've used (Elm and to a lesser extent Tachyons) are __so much fun__!
- It has pretty close ties to FAC.
- I've learnt so much from the `learn-` repos and would love to contribute to the next generation of `me`s.
- It's a very active community.

**Comment by ZooeyMiller** [comment] 2017-06-12 21:59
I just realised I have another question, when can those applying/who fulfil the prerequisites of the apprenticeship expect to hear back from dwyl?

**Comment by nelsonic** [comment] 2017-06-13 08:10
@ZooeyMiller you and @finnhodgkin are the only people who have show an interest (_so far_)
Both of you have made the time to:
+ [x] respond to the "AMA" questions ❓ 
+ [x] submit a PR improving a @dwyl learning resource and ❤️ 
+ [x] ["starred"](https://github.com/dwyl/contributing/stargazers) the "Contributing Guide" to demonstrate that you've read/understood it. ⭐️ 
So you gents are _in_. ✅ 

We `start` on **Monday 19**<sup>th</sup> June **09:00**. 🕘 

> FYI: I'm at my desk (_upstairs at 16 Palmers Road_) by 06:30 _every_ day.
Who ever arrives "_early_" gets more time from/with me (_if that's of any interest to you..._)

## `before` Monday 📆 

If you have "_free time_" this week and want to "_prepare_", take a look at this list: https://github.com/dwyl/the-book/issues/69 📚 
There are _many_ gaps in our documentation and if you are able to make a contribution to remedying that it will be _very much_ appreciated! 👍 

But otherwise "_rest up_" because the learning curve is going to be _intense_. 🎢

**Comment by antoniotrkdz** [comment] 2017-06-13 09:07
Hi Dwyl,
I was starting the AMA questionnaire now, but I would like to know:

Do you have any more spaces?
How long does the intern lasts?

Thanks!

**Comment by antoniotrkdz** [comment] 2017-06-13 14:02
_Who are you?_
I am Antonio Trabalza

_What is your "story" (or "journey") so far?_
I studied Neuropsychology at University of Rome and I then started a PhD in Psychobiology.
Psychobiology is the study of behaviour to determine which are the biological basis underneath it.
I was intersted in the networks of neurons (brain cells) involved in learning and memory.
I ended up studying some molecules involve in how synapses are formed and maintained between neurons.

After defending (and subsequently publishing) my thesis I got a job at Imperial College London to study the molecular basis of Amyotrophic Lateral Sclerosis or Motor Neuron Disease.
The project was well funded and the people I was working for looked nice, but I soon discovered that the British academia (and acedemia in general) is a shark thank draining you to the last drop of blood and expecting you to do the same with others.
After reluctantly aceepting to play this bad game I realize that without connections I couldn't "survive".

Since then on I tried hard to do some more research, but I felt I was changing to a worse person that I was before I started.
I always been using Linux and I am passionate about technology, so I got interested on coding and I started attending (Linux) meetups.
There I met nice people and eventually one of them told me about Fouders & Coders and here I am finishing FAC10 an looking to improve! 

_What did you like/dislike about working there?_
I liked the complexity of the problems to solve, the (rare) feeling to be pushing the boundaries of human knowledge forward and knowing I was working for the common good.

I disliked the shallowness of the people involved in academic research and how the whole system if f*#@ed so badly that is beyond any hope of recovery.

_What did you learn (both good and bad!) while there?_
I learnt loads of things, coding related I learnt how to automate Image microscope image analysis with a tool based on Java.
I learn how complexity lies in simplicity.
I hated to learn to act as an competitive awful person and what is the true meaning of stress, deception and being miserable.

_What do you want to do with the next 2 years of your life?_
In January 2017 my daugther is born and my life changed, now everything is not about my life, but about hers. I would like to get very good at coding to become a Freelancer.
This would give me flexibility to spend time to educate my children and choice on where to live. 

_Where do you want to live?_
In order: Italy, Switzerland, Netherlands, Denmark, UK (but only satisfiyng some conditions).

_Is there a "Real World Problem" you would like to solve?_
I don't think that there is enough space here to list all the problems that I would like to solve...
One thing I would like to put in place would be a sytem to provide a guaranteed minimal salary to anybody (the so called citizenship income), from birth to death. It has to be a stigma-free thing (as opposed to benefits) and be percieved as compensation to "be a good citizen", in any way people can find to give form to this statement.

_What is your personal connection to the problem?_
I feel my choices and some of others around me would be much better without the stress and fear related to modern money-centered society.
I think this "revolution" needs technology to happen, if I know technology I can help more.

_Why do you want to work with @dwyl specifically (as opposed to the millions of other options you have) ?_
Because I find everyone at dwyl to be good people.
Because I breathe open source and open knowledge.
Because it gives me opportunity to learn nice things.
Because gives me the opportunity to help FAC.
Beacuse it could help me to find a place to live and work from in the future.

**Comment by mattlub** [comment] 2017-06-13 16:51
> Who are you?

I'm Matt- one of the first graduates from FAC Nazareth 😄 . I like problem solving and making cool things, learning to do stuff, teaching, juggling and table tennis (among many other things).

> What is your "story" (or "journey") so far?

I decided to go to Nazareth to do Founders and Coders as I was really interested to get involved and help out with something new, exciting and relatively unknown, while at the same time of course gaining the skills to allow me to work as a web developer. Before Founders and Coders, I'd tried various different things, and admittedly was always feeling a bit unsure of what I really wanted to do:
- recently, driving a pizza van and making pizzas- I really liked the customer facing aspect of this, all round good fun, but not so good long term
- working for a software company in the finance industry- this was a bit of a struggle, I was not working on anything in particular and found it hard to get interested in the product. I guess I learnt a fair amount- some technical stuff relevant to what I do now, and to try more carefully to make sure I work at the right sort of place in the future.
- working for my local council- I enjoyed working as part of a close-knit team with lovely people, but unfortunately I didn't enjoy the work as it wasn't particularly interesting or challenging. 
Before all this I did a maths degree- I was mainly interested in the more abstract courses and the sort of curious questions you could talk about with non-mathematicians. The course was good though and also gave me a good logical base on which to start coding.

> What do you want to do with the next 2 years of your life?

I don't often think too far into the future, but right now I'd love to work for a while with some more senior people, as I think I still have loads to learn, and working with more experienced people is such a great way to develop. I'm also really excited about the future of Founders and Coders and would be definitely interested in helping to set up a new campus somewhere in the near future, having loved the experience of Nazareth.

> Where do you want to live?

I'm quite keen to move to Brighton and/or Bristol for a while, and have also often thought about moving abroad, maybe to Spain.

> Is there a "Real World Problem" you would like to solve?

I generally don't think too much about solving large-scale problems, but one thing which comes to mind is the problem of lack of community feeling nowadays, especially in London. I'm not sure I could narrow down the problem particularly, (or think about solving it with tech, maybe it's even partly caused by tech), but I feel it is a shame and something which we have lost.

> What is your personal connection to the problem?

I guess I personally feel the problem myself slightly, and know a fair few people who I think feel similarly.

> Why do you want to work with @dwyl specifically (as opposed to the millions of other options you have) ?

- they care a lot about helping and teaching and align with my values
- I would like to learn more elm 😄 
- I can be close to FAC for a while and stay involved there.
- the mini projects sound cool (esp. the map).
- future potential for remote working :)

**Disclaimer**: I'm not free from Tues 20th - Monday 26th, could this be a block? 
I would be up for doing extra prep during the rest of this week if that would help, and could also come in on the Monday (19th), or otherwise starting on the Tuesday 27th is the earliest I'm free.

**Comment by innov8tor3** [comment] 2017-06-16 08:52
Hi all ...

I am happy to answer the questionnaire, because what I see here is so fantastic. But I suspect - as usual - I don't quite fit the exact need here.

In particular, I spend a great deal of time in a Facebook group supporting folk who are looking to run **_real world projects_**, on quite different levels.

That support time means my ability to learn code - and back in the day, I was a COBOL man, and could even still do some SQL if it were needed, maybe - is limited.

Just on the real world projects, because it is one aspect mentioned here - and I'm suggesting it can be a drill down element, and would love to discuss this - I see the UK with a 150 year old, one size fits all education system, which my daughter in particular has fallen out of. Her future is therefore more uncertain than 95% of the population. I also fear for the very angry small Islamic boy next door.  

We also have a health system that has become far too organic as a system, exhibiting cancerous growth based on more and more people, instead of being able to focus on specific topics eg using technology, and yet still be able to successfully navigate the mire of legislation that had grown up.

In respect of real world projects, I have over 30 projects where any kind of overlap with folk in GitHub would be amazing. They are not all Education and Health, but a good number are. Very, very happy to discuss these if there might be any use to teams here or in the wider GitHub community.

I should also mention the Facebook community - I'm an unpaid moderator - focuses very specifically on **_real world issues_**, and that certainly includes Education and Health, and also Global Ecology.

I apologise for not answering the specific questions in a specific way, but feel from long experience that sometimes raw data doesn't necessarily join the dots as effectively as it might.

Thanks for listening.

On Twitter, and apologies again for my own limitations, I'm @innov8tor3. I mostly participate in mainstream social media, due to the huge audiences, and am still struggling with the structure, culture and tips and tricks here on GitHub. Hence any response here is likely to be slow. Sorry, I wish I had the resources to do more.

Again, thanks.

**Comment by innov8tor3** [comment] 2017-06-16 09:16
@ZooeyMiller 

In my mind there is a clear link between self doubt and the ability to be creative.

How do we learn new stuff? Mainly by doubting that we know everything, and even doubting knowledge we thought we understood before. That's all quite an uncertain feeling. But when something makes sense, we sometimes have to be willing to lose some existing beliefs.

If we think of all those people exuding self belief, are they actually harder to persuade when something, we might feel, is going in the wrong direction?

I do love the work done by Richard St John, the 4 minute Ted Talk on the 8 success characteristics.

And one of them is Challenge. Can we be open to question, even from ourselves? And is this actually an important survival instinct? Are we doing the right thing?

What I'm tying to say, in my woolly way, is that self doubt may not always be a bad thing.

:)

**Comment by nelsonic** [comment] 2017-06-19 07:44
@antoniotrkdz my _understanding_ is that you were working with @freelancedad on https://github.com/freelancedad/Freelancedad after the F&C Course ...?

@mattlub thanks for your great contribution(s) to: https://github.com/dwyl/learn-tachyons 🎉 
Tuesday 27th is fine, but I will only be in London for 2 days so we will have to pair _remotely_. 

@innov8tor3 😉 

@ZooeyMiller / @finnhodgkin let me know when you arrive this morning. 🕘 
If nobody is downstairs @ 16 Palmer's Road call my mobile and I will come downstairs to open (headphones cancel/mute door knocking..._)

**Comment by iteles** [comment] 2017-06-19 07:59
@mattlub FYI, your apprenticeship may have to be shorter than 4 weeks on account of a certain wedding 🙈 but we will confirm this with you asap.

**Closed by iteles** 2017-06-19 07:59 UTC
Labels: question

**Comment by antoniotrkdz** [comment] 2017-06-19 14:42
@nelsonic Thank you for your reply.
Due to changes of circumstances the frelancedad project was delayed to future time to be determined.
That happened during the past 2-3 weeks, which, together with the reasons explayned in my profile, brought me to consider application to dwyl internship. Cheers!
