### ISSUE TITLE
Create Automated Invoicing MVP

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#302] opened 2017-05-08 12:41 UTC
Create Automated Invoicing MVP

This is an invoicing system utilising Google Docs and Autocrat to automate our current internal processes for managing contractor invoices

**Comment by Jbarget** [comment] 2017-05-10 13:01
Example of an invoicing app (not automated though):

I use this currently to manage my invoices, their MVP is really great and just does what it needs to with no distractions. https://www.getalbert.com/

**Comment by nelsonic** [comment] 2017-05-10 13:02
@Jbarget can you _summarise_ the features you use most _and_ any you've _wanted_ and not had?

**Comment by iteles** [comment] 2017-05-10 13:15
@markwilliamfirth A few details on what you're thinking would be good as I imagine this one is quite interesting for people and can be interpreted in many different ways!

**Comment by SimonLab** [comment] 2017-05-10 13:20
@Jbarget the application seems nice but 

"Albert on Android.
We are working hard to bring Albert to Android. 
Leave your email, and we will notify you when it is ready."

and I don't think there is a web app at the moment.

**Comment by Jbarget** [comment] 2017-05-10 13:45
yep there is no web app, i use it as a ios app

Features:
- ability to create invoice
- ability to sett your account (image, bank details, name)
- ability to view outstanding invoices
- ability to view paid invoices
- ability to duplicate a previous invoice
- ability to preview invoice in-app
- ability to send invoice history to email (csv attachment)

Desired Functionality on top:
- ability to set financial year dates
- ability to sort invoices by financial year
- ability to send invoice history by financial year
- ability to edit the date an invoice was paid

**Comment by markwilliamfirth** [comment] 2017-05-24 14:06
MVP has been created:

Contractors can submit their invoices [here](https://docs.google.com/a/dwyl.com/forms/d/17cZBuustmgYNj5AsuDNNb3tBanAronavCtn6O4KG1Wg/edit).

@Cleop please could you test when you run your next invoice?

**Comment by markwilliamfirth** [comment] 2017-05-24 14:28
Form has been linked to [http://invoice.dwyl.com](http://invoice.dwyl.com)

**Comment by iteles** [comment] 2017-05-24 15:05
@markwilliamfirth When we last discussed this, the MVP was going to be a spreadsheet that each person can fill in and keep track of their hours in a consistent way that they can refer back to. 

What changed the plan?

**Comment by Jbarget** [comment] 2017-05-24 15:10
Personally (from a user's point of view) I'd much prefer this form than a spreadsheet. I detest spreadsheets

**Comment by markwilliamfirth** [comment] 2017-05-24 15:11
@iteles it's difficult to have a common spreadsheet if the rates aren't transparent yet (won't be an issue after https://github.com/dwyl/hq/issues/140 has been actioned)

People are still welcome to track their own hours in their own spreadsheets if they wish - they only need to copy the number of days into the form.

**Comment by sohilpandya** [comment] 2017-05-24 15:13
Hey @/all, I'm personally in favor of either a google doc or a spreadsheet over the form.

My current process has 4 steps:
1. change the date
2. update the number of days
3. update the total
4. Save and send

The above process using the form has a lot more steps than that. 😟

**Comment by markwilliamfirth** [comment] 2017-05-24 15:14
@sohilpandya would be good if you could time yourself doing both. I think this might be quicker. Don't knock it 'til you've tried it!

**Comment by sohilpandya** [comment] 2017-05-25 21:02
So the test results are back:
**form took 48 seconds**
**Personal Invoice took 1min 38sec including sending email to finance**

Hmmmm.

**Comment by sohilpandya** [comment] 2017-05-25 21:13
**Also please ignore those invoices.** I will be sending out the real one tomorrow 😟

**Comment by markwilliamfirth** [comment] 2017-05-26 08:22
@sohilpandya that's great! Will ignore them and wait for the proper one 👍 

I'm also thinking of adding some improvements to the form, for example making the projects a dropdown to speed that up rather than writing it in. Let me know if you (or anyone else here reading along) has other ideas to improve it.

I should also explain that there is good reasoning behind using this form for anyone who is confused about why I wanted to do this:
- It allows us to control the subject lines and content of dwyl contractor invoice emails, thereby allowing me to apply filters to the emails to automatically place them in my "pay queue"
- It only allows a pre-approved set of contractors to invoice us
- Contractor invoices now have a unique invoice code that allows us to easily identify them
- All invoice information is stored in a central spreadsheet allowing us to easily calculate total net pay, gross pay and VAT for all contractors - incredibly useful for the accounts
- The invoice system can be expanded to automatically generate invoices for founders & coders 10% contributions that dwyl makes to founders and coders for the founders and coders contractors
- All invoices are automatically generated and a link to the file is included in the spreadsheet next to each submission - this is amazing because we will now have a central index of all contractor invoices!
- All invoices follow the same format, thereby making it much quicker to identify and check invoices
- Calculations with contractor rates are calculated on our side by a central spreadsheet and merged into the invoice meaning human error is eliminated
- It removes the human error of forgetting to attach the invoice (i don't know if you noticed by you didn't attach it in the personal invoice method!) - this happens to us a lot and costs time both to us and the contractor
- Each contractor is assigned a contractor ID, which identifies them as either a UK-based individual, a UK-based company or a non-UK-based individual - this is really useful for tax/VAT purposes

There are a quite a few other reasons, but I want to stress that the main aim of this **MVP** is to automate our current internal processes for managing contractor invoices. For a few hours work I think it's doing that amazingly! The reduces administration load and therefore allows us to check and pay your invoices quicker. The fact that it's actually quicker for the contractor to submit as well is even better!

If others in this thread could trial it when they run their next invoice and provide feedback here that'd be great! Then we can assess whether we want to roll it out to everyone to use from now on.

Thanks!

**Comment by Jbarget** [comment] 2017-05-26 08:37
@markwilliamfirth nice work on the form. Also think a dropdown for project would be great. (adds consistency on your side of things). 

A question though, as a contractor I use that App i mentioned above called Albert. Would you expect me to fill out the form and also send a "dummy" invoice through the App too? (Im fine doing that)

**Comment by markwilliamfirth** [comment] 2017-05-26 08:58
@Jbarget the invoice you submit is also returned to you when you submit it - is it beneficial to send a dummy invoice from Albert to retain the records within Albert as well? Is it possible to add 'historical' invoices sent from yourself to clients using other systems to Albert when you sign up? Is Albert the only app you use? Do you also use Xero / Freeagent?

**Comment by Jbarget** [comment] 2017-05-26 09:53
1. Exactly, Albert has its own filing functionality that keeps track of my earnings to date so when it comes to tax time its really simple.
2. There is not functionality to upload historical invoices to their system. (Id still consider their app an MVP).
3. Albert is the only way I manage my finances
4. I dont use Xero or Freeagent

**Comment by markwilliamfirth** [comment] 2017-05-26 10:37
@Jbarget oooh that's a tough one! In that case you should continue to use albert, but if there comes a point where you're contracting for dwyl almost exclusively for an extended period of time then the dummy invoice thing would be appreciated from a dwyl internal accounting perspective, but not compulsory! Not sure how much more time it takes you to do both steps, but we shouldn't be transferring the accounting administration burden to you if you already have a system that works well for you! I see this MVP as being symbiotically useful for the people who don't currently have a system like that and are invoicing dwyl frequently

**Comment by Jbarget** [comment] 2017-05-26 10:52
just for the record id be happy using both Albert and the form as they are both quite easy tasks and make a big difference in administration/life admin time

**Comment by markwilliamfirth** [comment] 2017-05-26 11:13
@Jbarget then if you're happy to, that would be greatly appreciated!

**Comment by iteles** [comment] 2017-05-31 12:09
Another big plus for this system: invoices can be done from anywhere (e.g. on a mobile on your way home at the end of a sprint).

> This was I can do it on my way home. By the time I get home I've usually forgotten that I need to invoice for work.

**Comment by shouston3** [comment] 2017-05-31 22:42
Just used the system. Getting my thoughts out there:
+ Much easier and simpler than my previous way to invoicing 👍 - definitely a great improvement imo
+ How do I know that my invoice has successfully gone through? (other than a "success message")
  How will I know in a weeks time what I invoiced for and for how many days?
  I would like to get something like an email for confirmation which includes the amount of days I invoiced for to save it for my own invoicing records
+ I would like to see more transparency on where this is being sent to. Is it to a spreadsheet or to an email? When am I to expect a response?

Good progress, I'm looking forward to using this type of system in the future

**Comment by shouston3** [comment] 2017-05-31 22:58
Just used the system. Getting my thoughts out there:

+ Much easier than my previous way to invoicing 👍 definitely a great improvement imo
+ I didn’t realise that an email went through or to expect an email. Maybe in the google form success message have something like: “Invoice has been successfully sent. You should receive an email to: user@dwyl.io shortly”

Other than that it's really great, thanks @markwilliamfirth

**Comment by markwilliamfirth** [comment] 2017-06-01 10:07
@shouston3 thanks for the feedback! I've made the edit :)

Please keep the testing feedback coming guys! Is looking quite promising to roll this out to everyone

**Comment by Jbarget** [comment] 2017-06-01 10:43
@markwilliamfirth as an enhancement, would the system be able to send out monthly/yearly breakdowns for us self-employed people? Would go a long way when it came to tax-filing season

**Comment by markwilliamfirth** [comment] 2017-06-01 10:55
@Jbarget yes could definitely do that quite easily as everything is assigned per contractor and recorded in a spreadsheet

**Comment by iteles** [comment] 2017-06-02 00:16
@jbarget Excellent feedback! This MVP is getting the creative juices flowing nicely ;)

**Comment by sohilpandya** [comment] 2017-06-17 13:06
Just some more feedback. 

- add a date to the PDF and the email so that the user knows when they submitted the Invoice. I got an email at 1am at night and would like to know when I actually submitted it. 😊

**Comment by markwilliamfirth** [comment] 2017-06-19 08:30
@sohilpandya thanks for the feedback 😄  Done 👍

**Comment by iteles** [comment] 2017-06-19 08:59
@markwilliamfirth Let's roll this out to everyone in time for July?

**Comment by ZooeyMiller** [comment] 2017-06-23 08:42
@finnhodgkin and I have been pointed towards this to invoice for our apprenticeship, can we be added to the name dropdown?
(my legal name is Zachary Miller for any payment-y stuff)

**Comment by markwilliamfirth** [comment] 2017-06-23 10:20
@ZooeyMiller @finnhodgkin sure thing - if you send me your emails to mark(at)dwyl.com we can get you set up

**Comment by markwilliamfirth** [comment] 2017-06-23 10:51
@iteles yes let's roll it out, but first I'd be interested to get some more feedback from some dwylers who haven't used it yet

@katbow @harrygfox - would you be able to test this with a 'test invoice' and let me know how it could be improved and if there's any reason you wouldn't want to use it?

**Comment by katbow** [comment] 2017-07-01 22:12
@markwilliamfirth I tried it out. Definitely way simpler & quicker than my current process. I definitely prefer filling in a form like this instead of a spreadsheet.

One thing that would be nice to have but not necessary is to see the total calculated amount of the invoice before submitting. I noticed it in the email, but it's nice to see that I will be submitting an invoice for X amount before doing so.

P.s. The invoice I submitted is duplicate so can be disregarded for testing it out 🙂

**Comment by markwilliamfirth** [comment] 2017-07-03 12:24
@katbow great feedback!

Your email had been updated to the dwyl.com one and the invoicing system now emails from finance@dwyl.com

>see the total calculated amount of the invoice before submitting

This is a good idea, but it isn't currently possible with the current system without [making all dwyl contractor rates public](https://github.com/dwyl/hq/issues/140#issuecomment-303754455), which is still under discussion 👍

**Comment by markwilliamfirth** [comment] 2017-07-20 11:21
@RobStallion can you please test this out (invoice can be a test invoice) and let me know if there is any reason you wouldn't use this compared to your normal invoicing method? Any way it could be improved?

**Comment by harrygfox** [comment] 2017-07-31 11:51
@markwilliamfirth I love the new system! My only comment on improving would be to echo @Jbarget https://github.com/dwyl/hq/issues/302#issuecomment-305457399 - monthly & yearly breakdowns to help with taxings

**Comment by RobStallion** [comment] 2017-08-31 20:30
@markwilliamfirth SORRY I TOOK SO LONG 😞 

but this is fantastic. It is much faster and easier way of sending an invoice which will be less prone to human error (because as you know sometimes I would send my invoice email without the actual invoice attached 😖)

I am having the same issue @katbow mentioned [here](https://github.com/dwyl/hq/issues/302#issuecomment-312458368) where the email is being sent to my personal email from `mark@dwyl.com` but other than I have no faults.

**Comment by markwilliamfirth** [comment] 2017-09-01 04:09
thanks @RobStallion !

Yes - at the moment half of the emails are coming from finance and half from my email - not sure why it's done that - doesn't appear to be a pattern though - something needs to be reset!

**Comment by markwilliamfirth** [comment] 2017-09-01 17:20
Another bug spotted by @jackcarlisle - system does not currently allow for non-VAT registered companies

**Comment by ZooeyMiller** [comment] 2017-09-14 11:50
@finnhodgkin and I both sent our invoices for last week through on Friday 8th (on the google form), but neither of us received confirmation emails, did they go through?

**Comment by shouston3** [comment] 2017-09-14 12:36
I raised some invoices that weekend and didn't get an email response. I told @markwilliamfirth and got this response.

![screen shot 2017-09-14 at 13 35 15](https://user-images.githubusercontent.com/15983736/30430025-9df4d3ac-9951-11e7-888f-5a2203803c66.png)

**Comment by markwilliamfirth** [comment] 2017-09-18 11:20
To update this issue - the above error has been fixed now

**Comment by markwilliamfirth** [comment] 2017-11-13 17:46
Known issues 13 Nov 2017:
1. Some emails come from finance@dwyl.com some come from mark@dwyl.com (should all come from finance@dwyl.com) https://github.com/dwyl/hq/issues/302#issuecomment-326482374
2. On 10/24/2017 14:12:40 Finn submitted invoice DWYL1135, but the email did not come through, he had to submit again (DWYL1155)
3. The system generated two copies of DWYL1146 instead of one

**Comment by rub1e** [comment] 2018-01-16 11:00
Today I've...

* Updated the `cc` address to `finance@dwyl.com`
* Added the `Xero` address to `bcc` so the pdfs get sent there automatically
* Generally spent a looooong time figuring out how the process works, which I shall document in an `md` file and PR for the process handbook 😺

**Comment by iteles** [comment] 2018-01-16 11:14
@rub1e Thanks for the time estimates, update and finally getting some docs on this 🎉  (thanks @cleop also for starting us off with https://github.com/dwyl/process-handbook/issues/70#issuecomment-339266181. You're both 🌟 s

**Comment by rub1e** [comment] 2018-01-24 07:54
Now that https://github.com/dwyl/process-handbook/pull/84 is documented in the `process handbook`, do we want to close this issue and open a new one when we have time to update the Invoicing MVP, or keep this one open?

**Comment by iteles** [comment] 2018-01-24 08:44
@rub1e If we have things that we know need updating, let's open a new issue now. If not, then we can close this one and a new issue will be opened when things arise.

**Comment by rub1e** [comment] 2018-01-24 09:00
Closing as all current confirmed bugs have been resolved per https://github.com/dwyl/hq/issues/302#issuecomment-357926026

**Closed by rub1e** 2018-01-24 09:00 UTC
Labels: T1h, bug, finance, priority-2
