### ISSUE TITLE
Transfer to Santander

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/hq#264] opened 2017-02-27 12:59 UTC
Increase balance of operating account

**Comment by iteles** [comment] 2017-03-29 19:24
Done!

**Comment by iteles** [comment] 2017-05-21 21:37
Done 👍

**Comment by iteles** [comment] 2017-06-07 13:23
Done again

**Comment by iteles** [comment] 2017-08-19 11:43
Been like this since yesterday lunch time:
<img width="743" alt="screen shot 2017-08-19 at 12 43 02" src="https://user-images.githubusercontent.com/4185328/29486372-0ccd8ce0-84dc-11e7-8904-5d60eb6d0b43.png">

**Comment by iteles** [comment] 2017-08-23 12:15
Finally sorted their problems. Done.

Have also update Xero with all the latest payments.

**Comment by iteles** [comment] 2017-08-31 11:28
Done. Confirmed no further payments made from our clients since 21st Agust round of updates in Xero.

**Comment by markwilliamfirth** [comment] 2017-09-01 04:13
@iteles thanks - just a note to say that the balance probably needs to be significantly increased to prepare for #370

**Comment by iteles** [comment] 2017-09-05 02:51
Account balance significantly increased over the course of 3 working days given daily transaction caps.

**Comment by markwilliamfirth** [comment] 2017-09-05 10:51
This will need to be increased again post payment

**Comment by iteles** [comment] 2017-09-06 13:02
Done.

**Comment by iteles** [comment] 2017-09-22 07:47
And again, as well as updating all payments in Xero.

**Comment by markwilliamfirth** [comment] 2017-10-17 11:56
Balance is now in minus figures after recent order of Anker Mouse on Amazon

**Comment by iteles** [comment] 2017-10-18 16:54
I have been temporarily separated from my fob and when I tried to call cooperative bank yesterday, it appears our telephone banking has been mysteriously deactivated.

I expect to be reunited with my fob tonight but in the meantime have made a temporary loan from my personal account to cover any payments to dwylers that _must_ go out this week.

**Comment by markwilliamfirth** [comment] 2017-10-18 16:59
@iteles shall I open the metro account? #26

**Comment by markwilliamfirth** [comment] 2017-10-31 18:13
There isn't enough in the account to pay payroll

**Comment by iteles** [comment] 2017-10-31 18:27
Transferred and Xero updated with latest payments.

**Comment by iteles** [comment] 2017-10-31 18:28
Actually, decided to reopen so that I can make another transfer tomorrow after payroll is complete for the next set of payments.

**Closed** 2017-11-01 11:55 UTC
Labels: blocker, priority-1, T25m
